baseURL = "/"
title = "minimo"
author = " "
copyright = " "
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"



[params]
  description = " "
  blogSections = ["posts"]
  mainSections = ["blog"]
  logo = "/images/logo.png"
  logo_w = 119
# CSS Plugins
# [[params.plugins.js]]
# link = "lib/OwlCarousel2-2.3.4/dist/owl.carousel.min.js"

[[params.social]]
    disabled = true
    url = "#"
    title = "fb"
    icon = "fa-brands fa-facebook-f"
[[params.social]]
    display = true
    url = "#"
    title = "tw"
    icon = "fa-brands fa-twitter"
[[params.social]]
    display = true
    url = "#"
    title = "im"
    icon = "fa-brands fa-instagram"


[menu]
  [[menu.header]]
    name = "lifestyle"
    url = "/lifestyle/"
    weight = 1

  [[menu.header]]
    name = "photodiary"
    url = "/photodiary/"
    weight = 2

  [[menu.header]]
    name = "music"
    url = "/music/"
    weight = 3

  [[menu.header]]
    name = "travel"
    url = "/travel/"
    weight = 4

  [[menu.footer]]
    name = "Terms and conditions"
    url = "/terms/"
    weight = 1

  [[menu.footer]]
    name = "Privacy"
    url = "/privacy/"
    weight = 2
# [taxonomies]
# category = "categories"
# tag = "tags"
# series = "series"


[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true


[sidebar]
  [sidebar.fb]
    icon = "fa fa-afcebook"
    url="#"
  [sidebar.im]
    icon = "fa fa-afcebook"
    url="#"
  [sidebar.pinterest]
    icon = "fa fa-afcebook"
    url="#"

